Blogs.WebUI/Controllers/ChangePostController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Blogs.Domain.Abstract;
using Blogs.Domain.Entities;
using Blogs.WebUI.Models;

namespace Blogs.WebUI.Controllers
{
    public class ChangePostController : Controller
    {
        //
        // GET: /ChangePost/

        private IUserRepository _userRepo;
        private IPostRepository _postRepo;

        public ChangePostController(IPostRepository postRepo, IUserRepository userRepo)
        {
            _userRepo = userRepo;
            _postRepo = postRepo;
        }

        [Authorize]
        public ActionResult Index()
        {
            var user = _userRepo.Get.FirstOrDefault(u => u.Login == User.Identity.Name);
            if (User.IsInRole("manager"))
                return View(_postRepo.Get.Where(p => p.IdUser == user.Id));

            if (User.IsInRole("administrator"))
                return View(_postRepo.Get);
            return RedirectToAction("ListPost", "Post");
        }

        [HttpGet]
        public ActionResult Edit(int idPost)
        {
            var post = _postRepo.Get.FirstOrDefault(p => p.Id == idPost);
            if (post == null)
                return RedirectToAction("Error404", "Post");
            return View(post);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Post post)
        {
            if (!ModelState.IsValid)
                return View(post);

            var firstOrDefault = _userRepo.Get.FirstOrDefault(u => u.Login == User.Identity.Name);
            if (firstOrDefault != null)
                post.IdUser = firstOrDefault.Id;
            _postRepo.Update(post);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int idPost)
        {
            _postRepo.Delete(_postRepo.Get.FirstOrDefault(p => p.Id == idPost));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ViewResult CreatePost()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult CreatePost(CreatePostModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "For some reason you can not create a post");
                return View(model);
            }

            var firstOrDefault = _userRepo.Get.FirstOrDefault(u => u.Login == User.Identity.Name);
            if (firstOrDefault == null)
                return RedirectToAction("Error404", "Post");

            var post = new Post
            {
                Title = model.Title,
                Preview = model.Preview,
                Content = model.Content,
                UpdateTime = DateTime.Today,
                Tags = String.Concat('#', model.Tags),
                IdUser = firstOrDefault.Id
            };
            _postRepo.Create(post);
            return RedirectToAction("Index");
        }
    }
}

Blogs.WebUI/Views/ChangePost/CreatePost.cshtml
@model Blogs.WebUI.Models.CreatePostModel
@{
    ViewBag.Title = "AddPost";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="centerText">
    <h3><b>New post</b>
    </h3>
</div>
<center>
    @{Html.EnableClientValidation();}
    @{Html.EnableUnobtrusiveJavaScript();}

    @using (Html.BeginForm("CreatePost", "ChangePost", new { ViewBag.ReturnUrl },
        FormMethod.Post))
    {
        <div class="createPost">
            <div class="text-error">
                <b> @Html.ValidationSummary(true, "Account creation was unsuccessful. Please correct the errors and try again.")</b>
            </div>
            <div class="control-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(m => m.Title, new { @class = "input-large" })
                    <div class="text-error">
                        @Html.ValidationMessageFor(m => m.Title)
                    </div>
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(m => m.Preview, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextAreaFor(m => m.Preview, new { @class = "input-large" })
                    <div class="text-error">
                        @Html.ValidationMessageFor(m => m.Preview)
                    </div>
                </div>
            </div>


            <div class="control-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextAreaFor(m => m.Content, new { @class = "input-large" })
                    <div class="text-error">
                        @Html.ValidationMessageFor(m => m.Content)
                    </div>
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(m => m.Tags, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(m => m.Tags, new { @class = "input-large" })
                    <div class="text-error">
                        @Html.ValidationMessageFor(m => m.Tags)
                    </div>
                </div>
            </div>
        </div>
        <p>
            <input type="submit" class="btn btn-primary" value="Create" />
        </p>
    }

</center>

Blogs.WebUI/Views/ChangePost/Edit.cshtml
@model Blogs.Domain.Entities.Post
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="mytitle">
    <h2>Edit : @Model.Title</h2>
</div>
<div class="editorPost">
    @using (Html.BeginForm("Edit", "ChangePost",FormMethod.Post))
    {
        <b>@Html.EditorForModel()</b>
        <button type="submit" class="btn btn-primary"> Save</button>
    }
</div>

Blogs.WebUI/Views/ChangePost/Index.cshtml
@model IEnumerable<Blogs.Domain.Entities.Post>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<center>
    <div class="lineblue">
        <h3 class="infoText" style="color: white"><b>Post Information</b>
        </h3>
    </div>

    <div class="sosor">
        <div class="titlePost"><b>Title</b>
        </div>
        <div class="ActionsPost"><b>Actions</b>
        </div>
    </div>

    @foreach (var item in Model)
    {
        <div class="sosor">
            <div class="Link">@Html.ActionLink(item.Title, "Edit", new {IdPost = item.Id}, new {@class = "mylink"})</div>

            <div class="buttonDel">
                @using (Html.BeginForm("Delete", "ChangePost"))
                {
                    @Html.Hidden("idPost", item.Id)
                    <button type="submit" class="btn btn-primary">Delete</button>
                }
            </div>

            <div class="buttonEd">
                @using (Html.BeginForm("Edit", "ChangePost", FormMethod.Get))
                {
                    @Html.Hidden("IdPost", item.Id)
                    <button type="submit" class="btn btn-success">Edit</button>
                }

            </div>

        </div>
    }


    <p>@Html.ActionLink("Add a new post", "CreatePost")</p>
</center>