Blogs.WebUI/Models/CommentsViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Blogs.Domain.Entities;

namespace Blogs.WebUI.Models
{
    public class CommentCreateViewModel
    {
        public int Id { get; set; }
        public virtual Post Post { get; set; }
        public virtual  Users User{ get; set; }

        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Enter a text of the post")]
        public string Content { get; set; }
        public DateTime CreateTime { get; set; }
    }
}

Blogs.WebUI/Controllers/CommentsController.cs
using System.Linq;
using System.Web.Mvc;
using Blogs.Domain.Abstract;
using Blogs.Domain.Entities;
using Blogs.WebUI.Models;

namespace Blogs.WebUI.Controllers
{
    public class CommentsController : Controller
    {
        private IPostRepository _postRepos;
        private ICommentsRepository _repository;
        private IUserRepository _userRepo;

        public CommentsController(ICommentsRepository repoParam, IUserRepository userRepo, IPostRepository postRepos)
        {
            _repository = repoParam;
            _userRepo = userRepo;
            _postRepos = postRepos;
        }

        //
        // GET: /Comments/

        [HttpGet]
        public ViewResult CreateComment()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult CreateComment(CommentCreateViewModel model, int? idPost)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "For some reason you can not create a comment");
                return View(model);
            }

            if (!User.Identity.IsAuthenticated)
                return PartialView("CommentError");

            var firstOrDefault = _userRepo.Get.FirstOrDefault(u => u.Login == User.Identity.Name);
            if (firstOrDefault == null)
            {
                ModelState.AddModelError("", "For some reason you can not create a comment");
                return View(model);
            }
            var comment = new Comments
            {
                Content = model.Content,
                IdPost = idPost ?? 0,
                IdUsers = firstOrDefault.Id,
            };
            _repository.Create(comment);
            model.CreateTime = comment.CreateTime;
            model.User = firstOrDefault;
            model.Post = _postRepos.Get.FirstOrDefault(p => p.Id == idPost);

            if (Request.IsAjaxRequest())
                return PartialView("Comment", model);

            return RedirectToAction("AllPost", "Post", new {idPost});
        }

        [HttpPost]
        public ActionResult DeleteComment(int? idComment, int? idPost)
        {
            if (!User.IsInRole("administrator") || idComment == 0)
                return RedirectToAction("AllPost", "Post", new {idPost});
            if (idComment != null)
                _repository.Delete(idComment);
            return RedirectToAction("AllPost", "Post", new {idPost});
        }
    }
}

Blogs.WebUI/Views/Comments/Comment.cshtml
 @model Blogs.WebUI.Models.CommentCreateViewModel

 @using (Html.BeginForm("DeleteComment", "Comments",FormMethod.Post))
 {
     @Html.Hidden("idPost", Model.Post.Id)
     @Html.Hidden("idComment", Model.Id)
     <button class="buttonDeleteComment" type="submit">x</button>
 }
<p class="com"> Сomment by <a href="@Url.Action("GetAllPostByUser", "Post", new { idUser = Model.User.Id })"> @Model.User.Login </a>@Model.CreateTime  </p>
    <p class="content"><b>@Model.Content</b></p>

    <hr>

Blogs.WebUI/Views/Comments/CommentError.cshtml
<div class="alert alert-error">
    <b> Comment can put only authorized users </b>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>

Blogs.WebUI/Views/Comments/CreateComment.cshtml
@model Blogs.WebUI.Models.CommentCreateViewModel

@{
    Layout = null;

}
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<h5 class="muted"><b>Please enter comment</b></h5>

    @using (Ajax.BeginForm( "CreateComment", "Comments", new { idPost = ViewBag.ReturnUrl }, new AjaxOptions { HttpMethod = "post", UpdateTargetId = "comment", InsertionMode = InsertionMode.InsertBefore })) {
    <div class="control-group">
        <div class="controls">
            @Html.TextAreaFor(m => m.Content, new { @class = "input-large" })
            <div class="text-error">
                <b>@Html.ValidationMessageFor(m => m.Content)</b>
            </div>
        </div>
    </div>

    <p>
        <input type="submit" class="btn btn-primary" value="Ок" />
    </p>
}